Constrain WordPressShared dependency to iOS platform only
This prevents builds failing with:

> error: the library 'CoreAPI' requires macos 10.13, but depends on the
> product 'WordPressShared' which requires macos 12.0; consider changing
> the library 'CoreAPI' to require macos 12.0 or later, or the product
> 'WordPressShared' to require macos 10.13 or earlier.

WordPressShared internally depends on the SwiftLint plugin, which
explicitly declares a macOS version.