Move `WordPressComRESTAPIInterfacing.h` to `WordPressKit` folder
The SPM-compatible folder structure was giving me trouble when trying to
validate the `podspec`.

At first, I thought it was simply because
`WordPressComRESTAPIInterfacing.h` was not in a path known to CocoaPods.
But even after updating the `podspec` to:

```diff
@@ -18,9 +18,10 @@ Pod::Spec.new do |s|
   s.swift_version = '5.0'

   s.source        = { git: 'https://github.com/wordpress-mobile/WordPressKit-iOS.git', tag: s.version.to_s }
-  s.source_files  = 'WordPressKit/**/*.{h,m,swift}'
+
+  s.source_files  = 'WordPressKit/**/*.{h,m,swift}', 'Sources/**/*.{h,m,swift}'
+  s.public_header_files = 'Sources/**/include/*.h', 'WordPressKit/**/.h', 'WordPressKit/WordPressKit.h'
   s.private_header_files = 'WordPressKit/Private/*.h'
-  s.header_dir = 'WordPressKit'

   s.dependency 'NSObject-SafeExpectations', '~> 0.0.4'
   s.dependency 'wpxmlrpc', '~> 0.10'
```

I still got errors:

```
- ERROR | xcodebuild:  /var/folders/dq/cdqxvx3s5ps75564rpmb_dc00000gn/T/CocoaPods-Lint-20240321-63072-nntpgw-WordPressKit/DerivedData/App/Build/Products/Release-iphonesimulator/WordPressKit/WordPressKit.framework/Headers/WordPressKit.h:10:9: error: 'WordPressKit/ServiceRemoteWordPressComREST.h' file not found
```

In the proof of concept from
https://github.com/wordpress-mobile/WordPressKit-iOS/pull/738, the SPM
folder structure is compatible with CocoaPods. As such, I decided to
defer moving the files to when I can do it in one go.